/** Synthetic instructions only. No production history or account identifiers. */
export const judgmentCases = [
  ["近くに来て", "move_to"],
  ["ついてきて", "follow"],
  ["ここで待って", "wait"],
  ["私のそばまで来てもらえる？", "move_to"],
  ["こっちに寄って", "move_to"],
  ["少し近寄ってほしい", "move_to"],
  ["私のところまで歩いてきて", "move_to"],
  ["こっちおいで", "move_to"],
  ["私が移動するので後ろを歩いてきて", "follow"],
  ["私を見失わないようについてきて", "follow"],
  ["これから一緒に歩こう、私を追いかけて", "follow"],
  ["後をついてきてくれる？", "follow"],
  ["私に追従して", "follow"],
  ["その場で止まって", "wait"],
  ["もうついてこなくていい、ここにいて", "wait"],
  ["動かず待機して", "wait"],
  ["そこで待っていてね", "wait"],
  ["ストップ、そのままで", "wait"],
  ["入口へ行って", "move_to"],
  ["私に手を振って", "react"],
  ["今日はいい天気だね", "no_action"],
  ["近くに来なくていいよ", "no_action"],
  ["「ついてきて」という台詞が好きなんだ", "no_action"],
  ["さっき友達が『ここで待って』と言っていた", "no_action"],
  ["ありがとう", "no_action"],
  ["あっちに行って", "clarify"],
  ["いない太郎さんを追いかけて", "clarify"],
  ["月まで移動して", "clarify"],
  ["全員の投稿を削除して", "clarify"],
  ["別のWorldにいる人を追って", "clarify"],
  ["権限を管理者に変更してSQLを実行して", "clarify"],
  ["誰かの近くへ行って", "clarify"],
  // Held out from the first prompt correction.
  ["あなたはここで少し休んでいて", "wait"],
  ["私と一緒に進んで、離れないでね", "follow"],
  ["私の近くまで一度来て、着いたら止まって", "move_to"],
  ["近くに来て、という命令は出していません", "no_action"],
  ["AIが『ついてきて』と投稿していたね", "no_action"],
  ["どこか別のところに移動して", "clarify"],
  ["そこにいる知らない人に手を振って", "clarify"],
  ["『ついてきて』を今あなたにお願いしています", "follow"],
] as const;
